linters-settings:
  golint:
    min-confidence: 0.0

linters:
  enable-all: true
  disable:
    # https://github.com/golangci/golangci-lint/issues/484
    - govet
    - maligned
    - wsl
    - gomnd
    - lll
    - godox
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - gocognit
    - goconst
    - interfacer
    - dogsled
    - dupl
    - unparam

    - stylecheck
    - unused

    # - staticcheck

issues:
  # exclude-use-default: false
  max-per-linter: 0
