linters-settings:
  golint:
    min-confidence: 0.0

linters:
  enable-all: true
  disable:
    # slow
    - gosimple
    - staticcheck
    - stylecheck
    - unparam
    - unused
    # bad
    - maligned
    - lll
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - interfacer
    - dupl
    # https://github.com/golangci/golangci-lint/issues/484
    - govet
    - funlen
    - godox
    - wsl
    - gocognit
    - dogsled
    - gomnd

  # fast: true
  # enable:
  #   - golint

issues:
  # exclude-use-default: false
  max-per-linter: 0
