dist: xenial

git:
  depth: false

language: go

env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - go: "1.13.x"
      env: PRIMARY=true
    - go: "1.12.x"
    - go: "tip"

  fast_finish: true
  allow_failures:
    - go: "1.12.x"
    - go: "tip"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - GO111MODULE=off go get -v -u github.com/mattn/goveralls
  - docker pull zikaeroh/postgres-initialized
  - docker pull nsqio/nsq

script:
  - if [ "$PRIMARY" = true ]; then
      go mod tidy;
      test -z "$(git status --porcelain go.mod go.sum)";
    fi
  - go test -race -covermode=atomic -coverprofile=coverage.txt ./...
  - if [ "$PRIMARY" = true ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
      export VERSION="r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)";

      docker build -t hortbot/hortbot --build-arg version=$VERSION .;
      docker push hortbot/hortbot;
      docker tag hortbot/hortbot hortbot/hortbot:$VERSION;
      docker push hortbot/hortbot:$VERSION;
    fi

after_success:
  - if [ "$PRIMARY" = true ]; then
      bash <(curl -s https://codecov.io/bash);
      $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.txt;
    fi
