dist: xenial

git:
  depth: false

language: go

cache:
  directories:
   - $GOPATH/pkg

env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - go: "1.13.x"
      env: PRIMARY=true
    - go: "tip"

  fast_finish: true
  allow_failures:
    - go: "tip"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - GO111MODULE=off go get -v -u github.com/mattn/goveralls
  - docker pull zikaeroh/postgres-initialized
  - docker pull nsqio/nsq

script:
  - go mod download
  - if [ "$PRIMARY" = true ]; then
      go mod tidy;
      test -z "$(git status --porcelain go.mod go.sum)";
    fi
  - go test -race -covermode=atomic -coverprofile=coverage.txt ./...
  - if [ "$PRIMARY" = true ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      bash <(curl -s https://codecov.io/bash);
      $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.txt;
    fi
