version: "3"

services:
  irc:
    image: golang
    volumes:
      - .:/app:ro
      - $GOPATH/pkg/mod:/go/pkg/mod:ro
    working_dir: /app
    command: go run -mod=readonly -v ./cmd/irc -c config/irc.ini -c config/twitch.ini
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    environment:
      - HB_DEBUG=true
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  bot:
    image: golang
    volumes:
      - .:/app:ro
      - $GOPATH/pkg/mod:/go/pkg/mod:ro
    working_dir: /app
    command: go run -mod=readonly -v ./cmd/bot -c config/bot.ini -c config/twitch.ini
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    environment:
      - HB_DEBUG=true
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  web:
    image: golang
    volumes:
      - .:/app:ro
      - $GOPATH/pkg/mod:/go/pkg/mod:ro
    working_dir: /app
    command: go run -mod=readonly -v ./cmd/web -c config/twitch.ini
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    ports:
      - "5000:5000"
      - "5001:5000"
    environment:
      - HB_DEBUG=true
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable

  db:
    image: zikaeroh/postgres-initialized

  redis:
    image: redis

  nsq:
    image: nsqio/nsq
    command: /nsqd

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
