# A prod-like configuration using "real" images.

version: "3"

services:
  irc:
    build: .
    volumes:
      - ./config:/config:ro
    command: irc -c /config/irc.ini -c /config/twitch.ini
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    environment:
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  bot:
    build: .
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    volumes:
      - ./config:/config:ro
    command: bot -c /config/bot.ini -c /config/twitch.ini
    environment:
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  web:
    build: .
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    volumes:
      - ./config:/config:ro
    command: web -c /config/twitch.ini
    ports:
      - "5000:5000"
    environment:
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  db:
    image: zikaeroh/postgres-initialized

  redis:
    image: redis

  nsq:
    image: nsqio/nsq
    command: /nsqd

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
