version: "3"

services:
  irc:
    image: golang
    volumes:
      - .:/app:ro
      - $GOPATH/pkg/mod:/go/pkg/mod:ro
    working_dir: /app
    command: go run -mod=readonly -v ./cmd/irc
    links:
      - db
      - redis
      - nsq
      - jaeger
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    environment:
      - HB_NICK=${HB_NICK:-}
      - HB_PASS=${HB_PASS:-}
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  bot:
    image: golang
    volumes:
      - .:/app:ro
      - $GOPATH/pkg/mod:/go/pkg/mod:ro
    working_dir: /app
    command: go run -mod=readonly -v ./cmd/bot
    links:
      - db
      - redis
      - nsq
      - jaeger
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    environment:
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831
      - HB_ADMINS=${HB_ADMINS:-}
      - HB_WHITELIST_ENABLED=${HB_WHITELIST_ENABLED:-}
      - HB_TWITCH_CLIENT_ID=${HB_TWITCH_CLIENT_ID:-}
      - HB_TWITCH_CLIENT_SECRET=${HB_TWITCH_CLIENT_SECRET:-}
      - HB_TWITCH_REDIRECT_URL=${HB_TWITCH_REDIRECT_URL:-}
      - HB_LASTFM_KEY=${HB_LASTFM_KEY:-}
      - HB_STEAM_KEY=${HB_STEAM_KEY:-}

  web:
    image: golang
    volumes:
      - .:/app:ro
      - $GOPATH/pkg/mod:/go/pkg/mod:ro
    working_dir: /app
    command: go run -mod=readonly -v ./cmd/web
    links:
      - db
      - redis
      - nsq
      - jaeger
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    ports:
      - "5000:5000"
      - "5001:5000"
    environment:
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831
      - HB_TWITCH_CLIENT_ID=${HB_TWITCH_CLIENT_ID:-}
      - HB_TWITCH_CLIENT_SECRET=${HB_TWITCH_CLIENT_SECRET:-}
      - HB_TWITCH_REDIRECT_URL=${HB_TWITCH_REDIRECT_URL:-}

  db:
    image: zikaeroh/postgres-initialized

  redis:
    image: redis

  nsq:
    image: nsqio/nsq
    command: /nsqd

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
