version: "3"

services:
  app:
    image: golang
    volumes:
      - .:/app:ro
      - gopath:/go
      - go-build:/root/.cache/go-build
    working_dir: /app
    command: go run -mod=readonly -v . single-proc
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    env_file:
      - config/bot.env
      - config/twitch.env
      - config/irc.env
    environment:
      - HB_DEBUG=true
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_DB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_WEB_ADMIN_AUTH=admin:admin

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable


  db:
    image: zikaeroh/postgres-initialized

  redis:
    image: redis

volumes:
  gopath:
  go-build:
