version: "3"

services:
  app:
    image: golang
    volumes:
      - .:/app:ro
      - gopath:/go
      - go-cache:/root/.cache/go-build
    working_dir: /app
    command: go run -mod=readonly -v . single-proc -c config/bot.ini -c config/twitch.ini -c config/irc.ini
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      - HB_DEBUG=true
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable


  db:
    image: zikaeroh/postgres-initialized

  redis:
    image: redis

volumes:
  gopath:
  go-cache:
