# A prod-like configuration using "real" images.

version: "3"

services:
  irc:
    build:
      dockerfile: ./docker/Dockerfile.irc
      context: .
    links:
      - db
      - redis
      - nsq
      - jaeger
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    environment:
      - HB_NICK=${HB_NICK:-}
      - HB_PASS=${HB_PASS:-}
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  bot:
    build:
      dockerfile: ./docker/Dockerfile.bot
      context: .
    links:
      - db
      - redis
      - nsq
      - jaeger
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    environment:
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831
      - HB_ADMINS=${HB_ADMINS:-}
      - HB_WHITELIST_ENABLED=${HB_WHITELIST_ENABLED:-}
      - HB_TWITCH_CLIENT_ID=${HB_TWITCH_CLIENT_ID:-}
      - HB_TWITCH_CLIENT_SECRET=${HB_TWITCH_CLIENT_SECRET:-}
      - HB_TWITCH_REDIRECT_URL=${HB_TWITCH_REDIRECT_URL:-}
      - HB_LASTFM_KEY=${HB_LASTFM_KEY:-}
      - HB_STEAM_KEY=${HB_STEAM_KEY:-}

  web:
    build:
      dockerfile: ./docker/Dockerfile.web
      context: .
    links:
      - db
      - redis
      - nsq
      - jaeger
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    ports:
      - "5000:5000"
    environment:
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_MIGRATE_UP=true
      - HB_REDIS=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831
      - HB_WHITELIST_ENABLED=${HB_WHITELIST_ENABLED:-}
      - HB_TWITCH_CLIENT_ID=${HB_TWITCH_CLIENT_ID:-}
      - HB_TWITCH_CLIENT_SECRET=${HB_TWITCH_CLIENT_SECRET:-}
      - HB_TWITCH_REDIRECT_URL=${HB_TWITCH_REDIRECT_URL:-}

  db:
    image: zikaeroh/postgres-initialized

  redis:
    image: redis

  nsq:
    image: nsqio/nsq
    command: /nsqd

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
