version: "3"

services:
  irc:
    image: golang
    volumes:
      - .:/app:ro
      - gopath:/go
      - go-build:/root/.cache/go-build
    working_dir: /app
    command: go run -mod=readonly -v . irc
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    env_file:
      - config/irc.env
      - config/twitch.env
    environment:
      - HB_DEBUG=true
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_DB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  bot:
    image: golang
    volumes:
      - .:/app:ro
      - gopath:/go
      - go-build:/root/.cache/go-build
    working_dir: /app
    command: go run -mod=readonly -v . bot
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    env_file:
      - config/bot.env
      - config/twitch.env
    environment:
      - HB_DEBUG=true
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_DB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831

  web:
    image: golang
    volumes:
      - .:/app:ro
      - gopath:/go
      - go-build:/root/.cache/go-build
    working_dir: /app
    command: go run -mod=readonly -v . web
    depends_on:
      - db
      - redis
      - nsq
      - jaeger
    ports:
      - "5000:5000"
      - "5001:5000"
    env_file:
      - config/twitch.env
    environment:
      - HB_DEBUG=true
      - HB_DB=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - HB_DB_MIGRATE_UP=true
      - HB_REDIS_ADDR=redis:6379
      - HB_NSQ_ADDR=nsq:4150
      - HB_JAEGER_AGENT=jaeger:6831
      - HB_WEB_ADMIN_AUTH=admin:admin

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable

  db:
    image: zikaeroh/postgres-initialized

  redis:
    image: redis

  nsq:
    image: nsqio/nsq
    command: /nsqd

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "16686:16686"

volumes:
  gopath:
  go-build:
