name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/m-p/37033/thread-id/2780
        # go: ['1.14', '1.13', 'tip']
        go: ['1.14', '1.13']
    name: Go ${{ matrix.go }}

    steps:
      - uses: actions/checkout@v2-beta

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      - name: Install Go
        if: matrix.go != 'tip'
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go }}

      - name: Install Go tip
        if: matrix.go == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          ../bin/go version
          echo "::set-env name=GOROOT::$HOME/gotip"
          echo "::add-path::$HOME/gotip/bin"

      - name: Download Go modules
        run: go mod download

      - name: Pull docker images
        run: |
          docker pull zikaeroh/postgres-initialized
          docker pull nsqio/nsq

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=coverage.txt ./...

      - name: Run 1x benchmarks
        run: go test -run=- -bench . -benchtime=1x ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Check go.mod tidyness
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
          $(go env GOPATH)/bin/golangci-lint run --timeout 10m

  generate:
    name: go generate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: go generate
        run: |
          go generate ./...
          git diff --exit-code

      - name: genmodels
        run: |
          go run ./internal/cmd/genmodels
          git diff --exit-code


  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: [test, style, generate]

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0

      - name: Build image
        run: |
          export HB_VERSION="r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
          echo Building version $HB_VERSION
          docker build -t hortbot/hortbot --build-arg version=$HB_VERSION .
          echo "::set-env name=HB_VERSION::$HB_VERSION"

      - name: Push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag hortbot/hortbot hortbot/hortbot:$HB_VERSION
          docker push hortbot/hortbot
          docker push hortbot/hortbot:$HB_VERSION
