name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GO_DEV_VERSION: "1.14" # Recommended Go version for development.
  GOLANGCI_LINT_VERSION: "v1.29.0"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/m-p/37033/thread-id/2780
        # go: ["1.14", "tip"]
        go: ["1.14"]
        pkger: [false, true]
    name: Go ${{ matrix.go }} (${{ matrix.pkger && 'static' || 'live' }})

    steps:
      - uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      - name: Install Go
        if: matrix.go != 'tip'
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go }}

      - name: Install Go tip
        if: matrix.go == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          ../bin/go version
          echo "::set-env name=GOROOT::$HOME/gotip"
          echo "::add-path::$HOME/gotip/bin"

      - name: Download Go modules
        run: go mod download

      - name: Pull docker images
        run: |
          docker pull zikaeroh/postgres-initialized
          docker pull nsqio/nsq

      - name: Run pkger
        if: ${{ matrix.pkger }}
        run: |
          go run github.com/markbates/pkger/cmd/pkger list
          go run github.com/markbates/pkger/cmd/pkger -o internal/pkger

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=coverage.txt ./...

      - name: Run 1x benchmarks
        run: go test -run=- -bench . -benchtime=1x ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          name: Go ${{ matrix.go }}

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_DEV_VERSION }}-${{ hashFiles('**/go.sum') }}

      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ env.GO_DEV_VERSION }}

      - name: Check go.mod tidyness
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION
          $(go env GOPATH)/bin/golangci-lint run --timeout 10m

  generate:
    name: go generate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_DEV_VERSION }}-${{ hashFiles('**/go.sum') }}

      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ env.GO_DEV_VERSION }}

      - name: go generate
        run: |
          go generate ./...
          git diff --exit-code

      - name: genmodels
        run: |
          go run ./internal/cmd/genmodels
          git diff --exit-code

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: [test, style, generate]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        run: |
          export HB_VERSION="r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
          echo Version $HB_VERSION
          echo "::set-env name=HB_VERSION::$HB_VERSION"

      - name: Build / push image
        uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: hortbot/hortbot
          image_tag: "latest,${{ env.HB_VERSION }}"
          build_extra_args: "--build-arg=version=${{ env.HB_VERSION }}"
          push_image_and_stages: ${{ github.repository == 'hortbot/hortbot' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
