name: Test
# on: push

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.12.x, 1.13.x, tip]
    name: Go ${{ matrix.go }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0

      - name: Version
        run: echo "r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"

      - name: Go module cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go
        if: matrix.go != 'tip'
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Install gotip
        if: matrix.go == 'tip'
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          GO111MODULE=off go get -u -v golang.org/dl/gotip
          gotip download
          echo "::add-path::$HOME/sdk/gotip/bin"

      - name: Download Go modules
        run: go mod download

      - name: Check go.mod tidyness
        if: matrix.go == '1.13.x'
        run: |
          go mod tidy
          test -z "$(git status --porcelain go.mod go.sum)"

      - name: Pull docker images
        run: |
          docker pull zikaeroh/postgres-initialized
          docker pull nsqio/nsq

      - name: Environment info
        run: |
          go version
          go env
          docker info

      - name: Test
        run: go test -race -covermode=atomic -coverprofile=coverage.txt ./...
